const char __shader_fs_aa[] = 
"precision mediump float;\n"
"precision highp int;\n"
"\n"
"uniform frag\n"
"{\n"
"    highp mat3 scissorMat;\n"
"    highp mat3 paintMat;\n"
"    highp vec4 innerCol;\n"
"    highp vec4 outerCol;\n"
"    highp vec2 scissorExt;\n"
"    highp vec2 scissorScale;\n"
"    highp vec2 extent;\n"
"    highp float radius;\n"
"    highp float feather;\n"
"    highp float strokeMult;\n"
"    highp float strokeThr;\n"
"    int texType;\n"
"    int type;\n"
"};\n"
"\n"
"\n"
"uniform highp sampler2D tex;\n"
"\n"
"in highp vec2 ftcoord;\n"
"in highp vec2 fpos;\n"
"layout(location = 0) out highp vec4 outColor;\n"
"\n"
"highp float strokeMask()\n"
"{\n"
"    return min(1.0, (1.0 - abs(ftcoord.x * 2.0 + (-1.0))) * strokeMult) * min(1.0, ftcoord.y);\n"
"}\n"
"\n"
"highp float scissorMask(highp vec2 p)\n"
"{\n"
"    highp vec2 _87 = (-(abs((scissorMat * vec3(p, 1.0)).xy) - scissorExt)) * scissorScale + vec2(0.5);\n"
"    return clamp(_87.x, 0.0, 1.0) * clamp(_87.y, 0.0, 1.0);\n"
"}\n"
"\n"
"highp float sdroundrect(highp vec2 pt, highp vec2 ext, highp float rad)\n"
"{\n"
"    highp vec2 _35 = abs(pt) - (ext - vec2(rad, rad));\n"
"    return (min(max(_35.x, _35.y), 0.0) + length(max(_35, vec2(0.0)))) - rad;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    highp float _120 = strokeMask();\n"
"    if (_120 < strokeThr)\n"
"    {\n"
"        discard;\n"
"    }\n"
"    highp vec2 param = fpos;\n"
"    highp float _134 = scissorMask(param);\n"
"    if (_134 == 0.0)\n"
"    {\n"
"        return;\n"
"    }\n"
"    highp vec4 result;\n"
"    if (type == 0)\n"
"    {\n"
"        highp vec2 param_1 = (paintMat * vec3(fpos, 1.0)).xy;\n"
"        highp vec2 param_2 = extent;\n"
"        highp float param_3 = radius;\n"
"        result = mix(innerCol, outerCol, vec4(clamp((feather * 0.5 + sdroundrect(param_1, param_2, param_3)) / feather, 0.0, 1.0))) * (_120 * _134);\n"
"    }\n"
"    else\n"
"    {\n"
"        if (type == 1)\n"
"        {\n"
"            highp vec4 color = texture(tex, (paintMat * vec3(fpos, 1.0)).xy / extent);\n"
"            if (texType == 1)\n"
"            {\n"
"                color = vec4(color.xyz * color.w, color.w);\n"
"            }\n"
"            if (texType == 2)\n"
"            {\n"
"                color = vec4(color.x);\n"
"            }\n"
"            highp vec4 _251 = color;\n"
"            highp vec4 _257 = (_251 * innerCol) * (_120 * _134);\n"
"            color = _257;\n"
"            result = _257;\n"
"        }\n"
"        else\n"
"        {\n"
"            if (type == 2)\n"
"            {\n"
"                result = vec4(1.0);\n"
"            }\n"
"            else\n"
"            {\n"
"                if (type == 3)\n"
"                {\n"
"                    highp vec4 color_1 = texture(tex, ftcoord);\n"
"                    if (texType == 1)\n"
"                    {\n"
"                        color_1 = vec4(color_1.xyz * color_1.w, color_1.w);\n"
"                    }\n"
"                    if (texType == 2)\n"
"                    {\n"
"                        color_1 = vec4(color_1.x);\n"
"                    }\n"
"                    result = (color_1 * _134) * innerCol;\n"
"                }\n"
"            }\n"
"        }\n"
"    }\n"
"    outColor = result;\n"
"}\n"
"\n";