const char __shader_fs_aa[] = 
"\n"
"uniform frag\n"
"{\n"
"    mat3 scissorMat;\n"
"    mat3 paintMat;\n"
"    vec4 innerCol;\n"
"    vec4 outerCol;\n"
"    vec2 scissorExt;\n"
"    vec2 scissorScale;\n"
"    vec2 extent;\n"
"    float radius;\n"
"    float feather;\n"
"    float strokeMult;\n"
"    float strokeThr;\n"
"    int texType;\n"
"    int type;\n"
"};\n"
"\n"
"\n"
"uniform sampler2D tex_smp;\n"
"\n"
"in vec2 ftcoord;\n"
"in vec2 fpos;\n"
"layout(location = 0) out vec4 outColor;\n"
"\n"
"float strokeMask()\n"
"{\n"
"    return min(1.0, (1.0 - abs(ftcoord.x * 2.0 + (-1.0))) * strokeMult) * min(1.0, ftcoord.y);\n"
"}\n"
"\n"
"float scissorMask(vec2 p)\n"
"{\n"
"    vec2 _85 = (-(abs((scissorMat * vec3(p, 1.0)).xy) - scissorExt)) * scissorScale + vec2(0.5);\n"
"    return clamp(_85.x, 0.0, 1.0) * clamp(_85.y, 0.0, 1.0);\n"
"}\n"
"\n"
"float sdroundrect(vec2 pt, vec2 ext, float rad)\n"
"{\n"
"    vec2 _33 = abs(pt) - (ext - vec2(rad, rad));\n"
"    return (min(max(_33.x, _33.y), 0.0) + length(max(_33, vec2(0.0)))) - rad;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    float _118 = strokeMask();\n"
"    if (_118 < strokeThr)\n"
"    {\n"
"        discard;\n"
"    }\n"
"    vec2 param = fpos;\n"
"    float _132 = scissorMask(param);\n"
"    if (_132 == 0.0)\n"
"    {\n"
"        return;\n"
"    }\n"
"    vec4 result;\n"
"    if (type == 0)\n"
"    {\n"
"        vec2 param_1 = (paintMat * vec3(fpos, 1.0)).xy;\n"
"        vec2 param_2 = extent;\n"
"        float param_3 = radius;\n"
"        result = mix(innerCol, outerCol, vec4(clamp((feather * 0.5 + sdroundrect(param_1, param_2, param_3)) / feather, 0.0, 1.0))) * (_118 * _132);\n"
"    }\n"
"    else\n"
"    {\n"
"        if (type == 1)\n"
"        {\n"
"            vec4 color = texture(tex_smp, (paintMat * vec3(fpos, 1.0)).xy / extent);\n"
"            if (texType == 1)\n"
"            {\n"
"                color = vec4(color.xyz * color.w, color.w);\n"
"            }\n"
"            if (texType == 2)\n"
"            {\n"
"                color = vec4(color.x);\n"
"            }\n"
"            bool _254 = texType == 3;\n"
"            bool _260;\n"
"            if (_254)\n"
"            {\n"
"                _260 = color.w == 1.0;\n"
"            }\n"
"            else\n"
"            {\n"
"                _260 = _254;\n"
"            }\n"
"            if (_260)\n"
"            {\n"
"                discard;\n"
"            }\n"
"            vec4 _266 = color;\n"
"            vec4 _272 = (_266 * innerCol) * (_118 * _132);\n"
"            color = _272;\n"
"            result = _272;\n"
"        }\n"
"        else\n"
"        {\n"
"            if (type == 2)\n"
"            {\n"
"                result = vec4(1.0);\n"
"            }\n"
"            else\n"
"            {\n"
"                if (type == 3)\n"
"                {\n"
"                    vec4 color_1 = texture(tex_smp, ftcoord);\n"
"                    if (texType == 1)\n"
"                    {\n"
"                        color_1 = vec4(color_1.xyz * color_1.w, color_1.w);\n"
"                    }\n"
"                    if (texType == 2)\n"
"                    {\n"
"                        color_1 = vec4(color_1.x);\n"
"                    }\n"
"                    result = (color_1 * _132) * innerCol;\n"
"                }\n"
"            }\n"
"        }\n"
"    }\n"
"    outColor = result;\n"
"}\n"
"\n";