const char __shader_fs_aa[] = 
"precision mediump float;\n"
"precision highp int;\n"
"\n"
"uniform highp vec4 frag[11];\n"
"uniform highp sampler2D tex_smp;\n"
"\n"
"in highp vec2 ftcoord;\n"
"in highp vec2 fpos;\n"
"layout(location = 0) out highp vec4 outColor;\n"
"\n"
"highp float strokeMask()\n"
"{\n"
"    return min(1.0, (1.0 - abs(ftcoord.x * 2.0 + (-1.0))) * frag[10].x) * min(1.0, ftcoord.y);\n"
"}\n"
"\n"
"highp float scissorMask(highp vec2 p)\n"
"{\n"
"    highp vec2 _109 = (-(abs((mat3(vec3(frag[0].xyz), vec3(frag[1].xyz), vec3(frag[2].xyz)) * vec3(p, 1.0)).xy) - frag[8].xy)) * frag[8].zw + vec2(0.5);\n"
"    return clamp(_109.x, 0.0, 1.0) * clamp(_109.y, 0.0, 1.0);\n"
"}\n"
"\n"
"highp float sdroundrect(highp vec2 pt, highp vec2 ext, highp float rad)\n"
"{\n"
"    highp vec2 _33 = abs(pt) - (ext - vec2(rad, rad));\n"
"    return (min(max(_33.x, _33.y), 0.0) + length(max(_33, vec2(0.0)))) - rad;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    highp float _142 = strokeMask();\n"
"    if (_142 < frag[10].y)\n"
"    {\n"
"        discard;\n"
"    }\n"
"    highp vec2 param = fpos;\n"
"    highp float _155 = scissorMask(param);\n"
"    if (_155 == 0.0)\n"
"    {\n"
"        return;\n"
"    }\n"
"    int _164 = int(frag[10].w);\n"
"    highp vec4 result;\n"
"    if (_164 == 0)\n"
"    {\n"
"        highp vec2 param_1 = (mat3(vec3(frag[3].xyz), vec3(frag[4].xyz), vec3(frag[5].xyz)) * vec3(fpos, 1.0)).xy;\n"
"        highp vec2 param_2 = frag[9].xy;\n"
"        highp float param_3 = frag[9].z;\n"
"        result = mix(frag[6], frag[7], vec4(clamp((frag[9].w * 0.5 + sdroundrect(param_1, param_2, param_3)) / frag[9].w, 0.0, 1.0))) * (_142 * _155);\n"
"    }\n"
"    else\n"
"    {\n"
"        if (_164 == 1)\n"
"        {\n"
"            highp vec4 color = texture(tex_smp, (mat3(vec3(frag[3].xyz), vec3(frag[4].xyz), vec3(frag[5].xyz)) * vec3(fpos, 1.0)).xy / frag[9].xy);\n"
"            int _294 = int(frag[10].z);\n"
"            if (_294 == 1)\n"
"            {\n"
"                color = vec4(color.xyz * color.w, color.w);\n"
"            }\n"
"            if (_294 == 2)\n"
"            {\n"
"                color = vec4(color.x);\n"
"            }\n"
"            bool _321 = _294 == 3;\n"
"            bool _327;\n"
"            if (_321)\n"
"            {\n"
"                _327 = color.w == 1.0;\n"
"            }\n"
"            else\n"
"            {\n"
"                _327 = _321;\n"
"            }\n"
"            if (_327)\n"
"            {\n"
"                discard;\n"
"            }\n"
"            highp vec4 _333 = color;\n"
"            highp vec4 _339 = (_333 * frag[6]) * (_142 * _155);\n"
"            color = _339;\n"
"            result = _339;\n"
"        }\n"
"        else\n"
"        {\n"
"            if (_164 == 2)\n"
"            {\n"
"                result = vec4(1.0);\n"
"            }\n"
"            else\n"
"            {\n"
"                if (_164 == 3)\n"
"                {\n"
"                    highp vec4 color_1 = texture(tex_smp, ftcoord);\n"
"                    int _364 = int(frag[10].z);\n"
"                    if (_364 == 1)\n"
"                    {\n"
"                        color_1 = vec4(color_1.xyz * color_1.w, color_1.w);\n"
"                    }\n"
"                    if (_364 == 2)\n"
"                    {\n"
"                        color_1 = vec4(color_1.x);\n"
"                    }\n"
"                    result = (color_1 * _155) * frag[6];\n"
"                }\n"
"            }\n"
"        }\n"
"    }\n"
"    outColor = result;\n"
"}\n"
"\n";