const char __shader_fs_aa[] = 
"\n"
"uniform frag\n"
"{\n"
"    mat3 scissorMat;\n"
"    mat3 paintMat;\n"
"    vec4 innerCol;\n"
"    vec4 outerCol;\n"
"    vec2 scissorExt;\n"
"    vec2 scissorScale;\n"
"    vec2 extent;\n"
"    float radius;\n"
"    float feather;\n"
"    float strokeMult;\n"
"    float strokeThr;\n"
"    int texType;\n"
"    int type;\n"
"};\n"
"\n"
"\n"
"uniform sampler2D tex_smp;\n"
"\n"
"in vec2 ftcoord;\n"
"in vec2 fpos;\n"
"layout(location = 0) out vec4 outColor;\n"
"\n"
"float strokeMask()\n"
"{\n"
"    return min(1.0, (1.0 - abs(ftcoord.x * 2.0 + (-1.0))) * strokeMult) * min(1.0, ftcoord.y);\n"
"}\n"
"\n"
"float scissorMask(vec2 p)\n"
"{\n"
"    vec2 _85 = (-(abs((scissorMat * vec3(p, 1.0)).xy) - scissorExt)) * scissorScale + vec2(0.5);\n"
"    return clamp(_85.x, 0.0, 1.0) * clamp(_85.y, 0.0, 1.0);\n"
"}\n"
"\n"
"float sdroundrect(vec2 pt, vec2 ext, float rad)\n"
"{\n"
"    vec2 _33 = abs(pt) - (ext - vec2(rad, rad));\n"
"    return (min(max(_33.x, _33.y), 0.0) + length(max(_33, vec2(0.0)))) - rad;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    float _118 = strokeMask();\n"
"    if (_118 < strokeThr)\n"
"    {\n"
"        discard;\n"
"    }\n"
"    vec2 param = fpos;\n"
"    float _132 = scissorMask(param);\n"
"    if (_132 == 0.0)\n"
"    {\n"
"        return;\n"
"    }\n"
"    vec4 result;\n"
"    if (type == 0)\n"
"    {\n"
"        vec2 param_1 = (paintMat * vec3(fpos, 1.0)).xy;\n"
"        vec2 param_2 = extent;\n"
"        float param_3 = radius;\n"
"        result = mix(innerCol, outerCol, vec4(clamp((feather * 0.5 + sdroundrect(param_1, param_2, param_3)) / feather, 0.0, 1.0))) * (_118 * _132);\n"
"    }\n"
"    else\n"
"    {\n"
"        if (type == 1)\n"
"        {\n"
"            vec4 color = texture(tex_smp, (paintMat * vec3(fpos, 1.0)).xy / extent);\n"
"            if (texType == 1)\n"
"            {\n"
"                color = vec4(color.xyz * color.w, color.w);\n"
"            }\n"
"            if (texType == 2)\n"
"            {\n"
"                color = vec4(color.x);\n"
"            }\n"
"            vec4 _254 = color;\n"
"            vec4 _260 = (_254 * innerCol) * (_118 * _132);\n"
"            color = _260;\n"
"            result = _260;\n"
"        }\n"
"        else\n"
"        {\n"
"            if (type == 2)\n"
"            {\n"
"                result = vec4(1.0);\n"
"            }\n"
"            else\n"
"            {\n"
"                if (type == 3)\n"
"                {\n"
"                    vec4 color_1 = texture(tex_smp, ftcoord);\n"
"                    if (texType == 1)\n"
"                    {\n"
"                        color_1 = vec4(color_1.xyz * color_1.w, color_1.w);\n"
"                    }\n"
"                    if (texType == 2)\n"
"                    {\n"
"                        color_1 = vec4(color_1.x);\n"
"                    }\n"
"                    result = (color_1 * _132) * innerCol;\n"
"                }\n"
"                else\n"
"                {\n"
"                    if (type == 4)\n"
"                    {\n"
"                        vec4 color_2 = texture(tex_smp, ftcoord);\n"
"                        float _326 = dFdx(ftcoord.x);\n"
"                        if (_326 < 0.0)\n"
"                        {\n"
"                            vec4 _331 = color_2;\n"
"                            vec4 _405 = _331;\n"
"                            _405.x = _331.z;\n"
"                            _405.z = _331.x;\n"
"                            color_2 = _405;\n"
"                        }\n"
"                        else\n"
"                        {\n"
"                            if (_326 == 0.0)\n"
"                            {\n"
"                                color_2 = vec4(((color_2.x + color_2.y) + color_2.z) * 0.3333333432674407958984375);\n"
"                            }\n"
"                        }\n"
"                        if (((color_2.w * _132) * innerCol.w) < 0.00390625)\n"
"                        {\n"
"                            discard;\n"
"                        }\n"
"                        result = vec4(color_2.xyz * innerCol.xyz + ((vec3(innerCol.w) - color_2.xyz) * outerCol.xyz), innerCol.w) * _132;\n"
"                    }\n"
"                }\n"
"            }\n"
"        }\n"
"    }\n"
"    outColor = result;\n"
"}\n"
"\n";