name: CI

on: [push]

env:
  BUILD_TYPE: release

jobs:
  build-windows:
    name: windows build
    runs-on: windows-latest
    steps:
      - name: Install NSIS
        shell: pwsh
        run: |
          irm https://xmake.io/psget.text | iex
          xmake --version
      - uses: actions/checkout@v4
      - name: pre-repo
        shell: pwsh
        run: |
          $env:path+=";C:\Users\$($env:username)\xmake"
          mkdir -p dist
      - name: build
        shell: pwsh
        run: |
          $env:path+=";C:\Users\$($env:username)\xmake"
          xmake f -c -y --example=y
          xmake build example.gl
          xmake build example.d3d11
          xmake build example.gles
          cp ./build/windows/x64/release/example.gl.exe ./dist/
          cp ./build/windows/x64/release/example.d3d11.exe ./dist/
          cp ./build/windows/x64/release/example.gles.exe ./dist/
      - uses: actions/upload-artifact@v4
        with:
          name: windows-${{ github.run_id }}
          path: |
            dist/example.gl.exe
            dist/example.d3d11.exe
            dist/example.gles.exe
  build-osx:
    name: macos build
    runs-on: macos-latest
    steps:
      - name: install-xmake
        run: |
          brew install xmake
          xmake --version
      - uses: actions/checkout@v4
      - name: pre-repo
        run: |
          mkdir -p dist
      - name: build
        run: |
          xmake f -a x86_64 -c -y --example=y
          xmake build example.gl
          xmake build example.metal
          xmake build example.gles
          cp ./build/macosx/x86_64/release/example.gl ./dist/
          cp ./build/macosx/x86_64/release/example.metal ./dist/
          cp ./build/macosx/x86_64/release/example.gles ./dist/
      - uses: actions/upload-artifact@v4
        with:
          name: osx-${{ github.run_id }}
          path: |
            dist/example.gl
            dist/example.metal
            dist/example.gles
  build-linux:
    name: linux build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: install-xmake
        run: |
          sudo apt-get install libglfw3-dev tree
          ./scripts/xmake-install.sh xmake-amd64.deb
          sudo apt-get install -y ./xmake-amd64.deb
          rm ./xmake-amd64.deb
          xmake --version
      - name: pre-repo
        run: |
          mkdir -p dist
      - name: build
        run: |
          xmake f -c -y --example=y
          xmake build example.gl
          xmake build example.gles
          cp ./build/linux/x86_64/release/example.gl ./dist/
          cp ./build/linux/x86_64/release/example.gles ./dist/
      - name: cert
        env:
          CERT_TEXT: ${{ secrets.CERT_TEXT }}
        run: |
          cd project/android
          echo "org.gradle.java.home=$JAVA_HOME_11_X64" >> gradle.properties
          echo $CERT_TEXT > cert.txt
          cat cert.txt | base64 -d > cert.tar.xz
          tar -xf cert.tar.xz
          rm cert.tar.xz cert.txt
          ls -lh keystore.properties release.keystore
          cd ../../
      - name: build-arm-so
        run: |
          xmake f -p android -a armeabi-v7a --ndk_sdkver=21 --ndk=${ANDROID_NDK} -y -c --example=y --pkg='sdl2'
          xmake build example.gles
      - name: build-arm64-so
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          xmake f -p android -a arm64-v8a --ndk_sdkver=21 --ndk=${ANDROID_NDK} -y -c --example=y --pkg='sdl2'
          xmake build example.gles
      - name: build-apk
        run: |
          export JAVA_HOME=$JAVA_HOME_11_X64
          cd project/android
          ./gradlew assembleDebug
          cp ./app/build/outputs/apk/debug/app-debug.apk ../../dist/app.apk
          cd -
      - uses: actions/upload-artifact@v4
        with:
          name: linux-${{ github.run_id }}
          path: |
            dist/app.apk
            dist/example.gl
            dist/example.gles
