name: CI

on: [push]

env:
  BUILD_TYPE: release

jobs:
  build-windows:
    name: windows build
    runs-on: windows-latest
    steps:
      - name: Setup Windows 10 SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
        with:
          sdk-version: 20348
      - name: Install NSIS
        shell: powershell
        run: |
          Invoke-Expression (Invoke-Webrequest 'https://xmake.io/psget.text' -UseBasicParsing).Content
          xmake --version
      - uses: actions/checkout@v3
      - name: pre-repo
        shell: powershell
        run: |
          $env:path+=";C:\Users\$($env:username)\xmake"
          xmake repo -a local https://github.com/zeromake/xrepo.git
      - name: build
        shell: powershell
        run: |
          $env:path+=";C:\Users\$($env:username)\xmake"
          xmake f -c -y --example=y
          xmake build example
          xmake build example_d3d11
  build-osx:
    name: macos build
    runs-on: macos-latest
    steps:
      - name: install-xmake
        run: |
          brew install xmake
          xmake --version
      - uses: actions/checkout@v3
      - name: pre-repo
        run: |
          xmake repo -a local https://github.com/zeromake/xrepo.git
      - name: build
        run: |
          xmake f -c -y --example=y
          xmake build example
          xmake build example_metal
  build-linux:
    name: linux build
    runs-on: ubuntu-latest
    steps:
      - name: install-xmake
        run: |
          sudo add-apt-repository ppa:xmake-io/xmake
          sudo apt update
          sudo apt-get install xmake build-essential glfw
          xmake --version
      - uses: actions/checkout@v3
      - name: pre-repo
        run: |
          xmake repo -a local https://github.com/zeromake/xrepo.git
      - name: build
        run: |
          xmake f -c -y --example=y
          xmake build example
